# Generated by Django 6.0.5 on 2026-05-20 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaModel',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('cpf', models.CharField(max_length=20)),
                ('data_nascimento', models.DateTimeField()),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='SituacaoPessoaModel',
            fields=[
                ('id_situacao_pessoa', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'def_situacao_pessoa',
            },
        ),
        migrations.CreateModel(
            name='TipoPessoaModel',
            fields=[
                ('id_tipo_pessoa', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'def_id_tipo_pessoa',
            },
        ),
        migrations.CreateModel(
            name='TipoPlanoModel',
            fields=[
                ('id_def_tipo_plano', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'def_tipo_plano',
            },
        ),
        migrations.CreateModel(
            name='TreinoModel',
            fields=[
                ('id_treino', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=500)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Treinos',
            },
        ),
        migrations.CreateModel(
            name='FuncionarioModel',
            fields=[
                ('pessoamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foxfit.pessoamodel')),
                ('data_admissao', models.DateTimeField()),
                ('cref', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Funcionarios',
            },
            bases=('foxfit.pessoamodel',),
        ),
        migrations.CreateModel(
            name='CobrancaModel',
            fields=[
                ('id_cobranca', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateTimeField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('id_pessoa', models.ForeignKey(db_column='id_pessoa', on_delete=django.db.models.deletion.CASCADE, to='foxfit.pessoamodel')),
            ],
            options={
                'db_table': 'Cobranças',
            },
        ),
        migrations.AddField(
            model_name='pessoamodel',
            name='id_situacao_pessoa',
            field=models.ForeignKey(db_column='id_situacao_pessoa', on_delete=django.db.models.deletion.PROTECT, to='foxfit.situacaopessoamodel'),
        ),
        migrations.AddField(
            model_name='pessoamodel',
            name='id_tipo_pessoa',
            field=models.ForeignKey(db_column='id_tipo_pessoa', on_delete=django.db.models.deletion.PROTECT, to='foxfit.tipopessoamodel'),
        ),
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('pessoamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foxfit.pessoamodel')),
                ('objetivo', models.CharField(blank=True, max_length=400, null=True)),
                ('peso_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('data_ultima_medidas', models.DateTimeField(blank=True, null=True)),
                ('observacao_medica', models.CharField(max_length=300)),
                ('id_tipo_plano', models.ForeignKey(db_column='id_tipo_plano', on_delete=django.db.models.deletion.PROTECT, to='foxfit.tipoplanomodel')),
                ('id_treino', models.ForeignKey(blank=True, db_column='id_treinoFK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foxfit.treinomodel')),
                ('id_instrutor', models.ForeignKey(blank=True, db_column='id_instrutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foxfit.funcionariomodel')),
            ],
            options={
                'db_table': 'Clientes',
            },
            bases=('foxfit.pessoamodel',),
        ),
    ]
