# Generated by Django 6.0.5 on 2026-05-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foxfit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientemodel',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='cobrancamodel',
            options={'verbose_name': 'Cobrança', 'verbose_name_plural': 'Cobranças'},
        ),
        migrations.AlterModelOptions(
            name='funcionariomodel',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='pessoamodel',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='situacaopessoamodel',
            options={'verbose_name': 'Situação de Pessoa', 'verbose_name_plural': 'Situações de Pessoa'},
        ),
        migrations.AlterModelOptions(
            name='tipopessoamodel',
            options={'verbose_name': 'Tipo de Pessoa', 'verbose_name_plural': 'Tipos de Pessoa'},
        ),
        migrations.AlterModelOptions(
            name='tipoplanomodel',
            options={'verbose_name': 'Tipo de Plano', 'verbose_name_plural': 'Tipos de Plano'},
        ),
        migrations.AlterModelOptions(
            name='treinomodel',
            options={'verbose_name': 'Treino', 'verbose_name_plural': 'Treinos'},
        ),
        migrations.AddField(
            model_name='funcionariomodel',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionariomodel',
            name='turno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
