# Generated by Django 6.0.5 on 2026-05-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foxfit', '0002_alter_clientemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoamodel',
            name='foto_perfil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
